const root = document.getElementById('root');
const modalTitle = document.getElementById('mtitle');
const modalBody = document.getElementById('mbody');
const S = { page:'home', token:localStorage.getItem('valeris_token')||'', user:null, data:null, balanceVisible:true };

const TASKS = [
 ['dailyCheckIn','Daily Check-in','Confirm today’s check-in and start your earning day.',50,'✓'],
 ['financialKnowledgeQuiz','Financial Knowledge Quiz','Answer three short financial knowledge questions.',100,'?'],
 ['investmentArticle','Read an Investment Article','Read a short lesson and share one takeaway.',75,'▤'],
 ['cryptoMemoryPuzzle','Crypto Memory Puzzle','Complete a matching-memory challenge.',80,'◈'],
 ['bitcoinJigsawPuzzle','Bitcoin Jigsaw Puzzle','Solve the educational word puzzle.',90,'⌘'],
 ['investmentEducation','Investment Education','Complete a mini learning module.',120,'◫'],
 ['completeSurvey','Complete Survey','Share your feedback through a real survey form.',60,'☷'],
 ['marketWatch','Market Watch','Review a market scenario and make a choice.',70,'↗'],
 ['budgetPlanner','Budget Planner','Build a simple balanced monthly budget.',85,'£'],
 ['securityCheck','Security Check','Pass a short account-security checklist.',65,'♜']
];
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>'£'+Number(n||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
const logo = `<img class="brand-mark" src="assets/valerisbank-logo.svg" alt="ValerisBank logo"><span>ValerisBank<small>EARN AND GROW</small></span>`;

async function api(path,opt={}){
  const headers={'Content-Type':'application/json',...(opt.headers||{})};
  if(S.token) headers.Authorization='Bearer '+S.token;
  const response=await fetch(path,{...opt,headers});
  const data=await response.json().catch(()=>({message:'Server error'}));
  if(!response.ok) throw Error(data.message||'Request failed');
  return data;
}
function go(page){S.page=page;render();window.scrollTo({top:0,behavior:'smooth'})}
function modal(title,body){modalTitle.textContent=title;modalBody.innerHTML=body;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function toast(message){let el=document.getElementById('toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';document.body.append(el)}el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3800)}
async function session(){if(!S.token)return;try{S.user=(await api('/api/me')).user;S.data=(await api('/api/me/data')).data}catch{S.token='';localStorage.removeItem('valeris_token')}}
async function refresh(){S.data=(await api('/api/me/data')).data;render()}
function totalBalance(d=S.data||{}){return Number(d.mainBalance||0)+Number(d.taskBalance||0)+Number(d.investmentBalance||0)+Number(d.investmentProfit||0)}
function activeInvestments(){return (S.data?.investments||[]).filter(i=>i.status==='active')}

function publicHeader(){return `<header class="header"><div class="container"><div class="logo logo-flex" onclick="go('home')">${logo}</div><nav class="nav"><a onclick="go('personal')">Personal</a><a onclick="go('products')">Products</a><a onclick="go('about')">About Us</a><a onclick="go('tasks')">Tasks</a><a onclick="window.open('https://t.me/ValerisManagement','_blank')">Support</a></nav><div class="actions"><button class="btn outline" onclick="go('login')">Login</button><button class="btn primary" onclick="go('signup')">Open an Account</button></div></div></header>`}
function footer(){return `<footer class="footer"><div class="container"><div class="footgrid"><div><div class="logo logo-flex">${logo}</div><p style="color:var(--muted);font-size:13px">A polished interactive accounts with separate member dashboards and saved data.</p></div><div><h4>Features</h4><a onclick="go('personal')">Personal dashboard</a><a onclick="go('tasks')">Participative tasks</a><a onclick="go('investment')">Investment</a></div><div><h4>Company</h4><a onclick="go('about')">About ValerisBank</a><a onclick="go('products')">Products</a></div><div><h4>Support</h4><a onclick="window.open('https://t.me/ValerisManagement','_blank')">Telegram Support</a></div></div><div class="copyright">© 2026 ValerisBank interface. Only your banking, investment or financial transactions are processed.</div></div></footer>`}
function shell(x){return publicHeader()+x+footer()}

function home(){return shell(`<main>
<section class="hero hero-pro"><div class="container hero-grid"><div class="reveal"><div class="kicker">Modern banking experience</div><h1>Grow Smarter.<br><span>Move Forward.</span></h1><p>Manage your personal dashboard, participate in interactive earning activities, track progress and explore investment in one polished ValerisBank experience.</p><div class="hero-buttons"><button class="btn primary" onclick="go('signup')">Open an Account</button><button class="btn outline" onclick="go('login')">Login</button></div><div class="trust-row"><span>◉ Secure environment</span><span>◉ Individual dashboards</span><span>◉ 24/7 support</span></div></div><div class="hero-visual reveal delay"><img src="assets/banking-visual.png" alt="Modern digital banking workspace"><div class="floating-card"><span>Portfolio Growth</span><strong>+30% Return</strong><small>After 24-hour.</small></div></div></div></section>
<section class="section section-soft"><div class="container"><div class="section-head"><div><div class="kicker">Everything connected</div><h2>One dashboard. More ways to participate.</h2></div></div><div class="cards"><div class="card feature-card"><div class="icon">▣</div><h3>Fund Wallet</h3><p>Test the one-time verification flow and see balances update on your own saved dashboard.</p></div><div class="card feature-card"><div class="icon">☷</div><h3>Participative Tasks</h3><p>Every reward now comes after completing a survey, quiz, puzzle, lesson or other activity.</p></div><div class="card feature-card"><div class="icon">↗</div><h3>Investment</h3><p>Track your 24-hour return investment, where capital and profit mature together.</p></div><div class="card feature-card"><div class="icon">◌</div><h3>Analytics</h3><p>Watch balances, earnings and activity through a visual earnings overview.</p></div></div></div></section></main>`)}

function auth(type){return `<main class="auth"><div class="auth-card reveal"><div class="logo logo-flex">${logo}</div><h1>${type==='login'?'Welcome back':'Open your account'}</h1><div class="notice">Only your money, banking or investment transactions are processed.</div><div id="authMsg"></div>${type==='signup'?`<div class="field"><label>First name</label><input id="firstName"></div><div class="field"><label>Last name</label><input id="lastName"></div><div class="field"><label>Country</label><input id="country"></div><div class="field"><label>Phone</label><input id="phone"></div>`:''}<div class="field"><label>${type==='login'?'Email or phone':'Email'}</label><input id="email"></div><div class="field"><label>Password</label><input id="pass" type="password"></div><button class="btn primary" onclick="${type==='login'?'login()':'signup()'}">${type==='login'?'Login':'Create Account'}</button><button class="btn outline back" onclick="go('home')">Back</button></div></main>`}
function msg(m){const e=document.getElementById('authMsg');if(e)e.innerHTML=`<div class="notice">${esc(m)}</div>`}
async function signup(){try{const r=await api('/api/signup',{method:'POST',body:JSON.stringify({firstName:firstName.value,lastName:lastName.value,country:country.value,phone:phone.value,email:email.value,password:pass.value})});S.token=r.token;localStorage.setItem('valeris_token',S.token);S.user=r.user;await refresh();S.page='dashboard';render()}catch(e){msg(e.message)}}
async function login(){try{const r=await api('/api/login',{method:'POST',body:JSON.stringify({identity:email.value,password:pass.value})});S.token=r.token;localStorage.setItem('valeris_token',S.token);S.user=r.user;await refresh();S.page='dashboard';render()}catch(e){msg(e.message)}}
async function logout(){try{await api('/api/logout',{method:'POST'})}catch{}S.token='';S.user=null;S.data=null;localStorage.removeItem('valeris_token');go('home')}

function appbar(){return `<div class="appbar"><div class="container"><div class="logo logo-flex" onclick="go('dashboard')">${logo}</div><div class="spacer"></div><div class="app-user"><span>Welcome, <b>${esc(S.user?.firstName||'Member')}</b></span><button class="profile-dot" onclick="go('profile')">${esc((S.user?.firstName||'M').slice(0,1))}</button><button class="btn app-logout" onclick="logout()">Logout</button></div></div></div>`}
function side(){return `<aside class="sidebar"><div class="side-brand">Member Area</div><button class="sidebtn ${S.page==='dashboard'?'active':''}" onclick="go('dashboard')">⌂ Overview</button><button class="sidebtn ${S.page==='fund'?'active':''}" onclick="go('fund')">▣ Fund Wallet</button><button class="sidebtn ${S.page==='tasks'?'active':''}" onclick="go('tasks')">☷ Tasks to Earn</button><button class="sidebtn ${S.page==='investment'?'active':''}" onclick="go('investment')">↗ Investment</button><button class="sidebtn ${S.page==='withdraw'?'active':''}" onclick="go('withdraw')">⇩ Withdraw</button><button class="sidebtn ${S.page==='transactions'?'active':''}" onclick="go('transactions')">≡ Transactions</button><h5>Account</h5><button class="sidebtn ${S.page==='profile'?'active':''}" onclick="go('profile')">◯ Profile</button><button class="sidebtn" onclick="window.open('https://t.me/ValerisManagement','_blank')">✈ Support</button><button class="sidebtn logout-side" onclick="logout()">↪ Logout</button></aside>`}
function appShell(x){return appbar()+`<div class="dashboard">${side()}<main class="dashmain"><div class="notice demo-notice">Balances, funding, withdrawals, tasks and investments are saved for the individual logged-in member.</div>${x}</main></div><nav class="mobile-nav"><button onclick="go('dashboard')">⌂<span>Home</span></button><button onclick="go('fund')">▣<span>Fund</span></button><button onclick="go('withdraw')">⇩<span>Withdraw</span></button><button onclick="go('tasks')">☷<span>Tasks</span></button><button onclick="logout()">↪<span>Logout</span></button></nav>`}
function acts(){return (S.data?.activity||[]).slice().reverse()}

function earningsChart(){const d=S.data||{};const task=Number(d.taskEarnings||0), profit=Number(d.investmentProfit||0), wallet=Number(d.mainBalance||0);const values=[Math.max(0,wallet*.12),Math.max(0,wallet*.18+task*.1),Math.max(0,wallet*.24+task*.25),Math.max(0,wallet*.32+profit*.2),Math.max(0,wallet*.42+task*.35),Math.max(0,wallet*.55+profit*.45),Math.max(0,totalBalance())];const max=Math.max(...values,1);const points=values.map((v,i)=>`${20+i*48},${170-(v/max)*125}`).join(' ');const area=`20,170 ${points} 308,170`;return `<div class="panel chart-panel"><div class="chart-head"><div><h3>Earnings Overview</h3><p>Wallet, task rewards and investment performance</p></div><span class="chart-chip">This period</span></div><div class="line-chart"><svg viewBox="0 0 320 190" preserveAspectRatio="none"><defs><linearGradient id="investmentFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#14B8A6"/><stop offset="1" stop-color="#14B8A6" stop-opacity="0"/></linearGradient></defs><path d="M20 40H308 M20 82H308 M20 124H308 M20 170H308" class="chart-grid-line"/><polygon points="${area}" class="chart-area"/><polyline points="${points}" class="chart-line"/>${values.map((v,i)=>`<circle cx="${20+i*48}" cy="${170-(v/max)*125}" r="4" class="chart-dot"/>`).join('')}</svg></div><div class="chart-legend"><span>Task earnings: <strong>${fmt(task)}</strong></span><span>Investment profit: <strong>${fmt(profit)}</strong></span><span>Total: <strong>${fmt(totalBalance())}</strong></span></div></div>`}

function dashboard(){const d=S.data||{};const total=totalBalance(d);const active=activeInvestments().length;return appShell(`<div class="dash-title"><div><div class="kicker">ValerisBank member dashboard</div><h1>Welcome back, ${esc(S.user?.firstName||'Member')}</h1><p>Your activity, rewards and portfolio in one place.</p></div><button class="btn secondary" onclick="refresh()">↻ Refresh</button></div><div class="stats"><div class="stat stat-highlight"><div class="label">Total Balance</div><div class="balance-row"><strong>${S.balanceVisible?fmt(total):'••••••••'}</strong><button class="balance-toggle" onclick="S.balanceVisible=!S.balanceVisible;render()">◉</button></div><small>${active} active investment ${active===1?'':'s'}</small></div><div class="stat"><div class="label">Task Earnings</div><strong>${fmt(d.taskBalance)}</strong><div class="label">Participative rewards • withdrawable</div></div><div class="stat"><div class="label">Investment Profit</div><strong>${fmt(d.investmentProfit)}</strong><div class="label">Settled after the maturity period</div></div></div><div class="quick quick-equal"><button class="btn secondary" onclick="go('fund')">＋ Fund Wallet</button><button class="btn secondary" onclick="go('withdraw')">⇩ Withdraw</button><button class="btn secondary" onclick="go('tasks')">☷ Tasks</button><button class="btn secondary" onclick="go('investment')">↗ Investment</button></div><div class="analytics-grid">${earningsChart()}<div class="panel summary-panel"><h3>Account Summary</h3><div class="summary-line"><span>Main wallet</span><strong>${fmt(d.mainBalance)}</strong></div><div class="summary-line"><span>Completed tasks</span><strong>${d.completedTasks||0}/10</strong></div><div class="summary-line"><span>Active investments</span><strong>${active}</strong></div><div class="summary-line"><span>Account</span><strong>${esc(S.user?.accountNumber||'')}</strong></div><button class="btn primary full-btn" onclick="go('tasks')">View Available Tasks</button></div></div><div class="panel activity-panel"><div class="chart-head"><div><h3>Recent Activity</h3><p>Saved to your individual member account</p></div><button class="text-btn" onclick="go('transactions')">View all</button></div><div class="tablewrap"><table class="table"><thead><tr><th>Description</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>${acts().slice(0,7).map(a=>`<tr><td>${esc(a.title)}</td><td>${esc(a.date)}</td><td class="${a.amount<0?'amount-out':'amount-in'}">${a.amount<0?'-':'+'}${fmt(Math.abs(a.amount))}</td><td><span class="pill ${a.status==='Pending'?'pending':'ok'}">${esc(a.status)}</span></td></tr>`).join('')||'<tr><td colspan="4">No activity yet.</td></tr>'}</tbody></table></div></div>`)}

function transactions(){return appShell(`<div class="dash-title"><div><h1>Transactions</h1><p>Saved account activity for this member.</p></div></div><div class="panel"><div class="tablewrap"><table class="table"><thead><tr><th>Description</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>${acts().map(a=>`<tr><td>${esc(a.title)}<small class="desc">${esc(a.description||'')}</small></td><td>${esc(a.date)}</td><td>${fmt(a.amount)}</td><td><span class="pill ${a.status==='Active'||a.status==='Pending'?'pending':'ok'}">${esc(a.status)}</span></td></tr>`).join('')||'<tr><td colspan="4">No activity yet.</td></tr>'}</tbody></table></div></div>`)}

function fund(){return appShell(`<div class="dash-title"><div><h1>Fund Wallet</h1><p>Generate a one-time verification code, then verify your test funding.</p></div></div><div class="card form-card"><div class="field"><label>Funding Amount (£)</label><input id="fundAmount" type="number" min="1" placeholder="Enter amount"></div><div class="fund-code-row"><div class="field grow"><label>Funding Verification Code</label><input id="fundCode" inputmode="numeric" maxlength="6" placeholder="Enter 6-digit code"></div><button class="btn secondary code-btn" onclick="generateCode()">Generate Code</button></div><div class="notice">code only: a new one-time code is generated for each request, expires after 5 minutes.</div><button class="btn primary full-btn" onclick="verifyFund()">Verify Funding</button></div>`)}
async function generateCode(){try{const r=await api('/api/test/verification-code',{method:'POST'});toast(r.message)}catch(e){toast(e.message)}}
async function verifyFund(){const amount=Number(document.getElementById('fundAmount')?.value);const code=document.getElementById('fundCode')?.value||'';if(!amount||amount<=0)return toast('Enter a valid funding amount.');if(!/^\d{6}$/.test(code))return toast('Enter the 6-digit verification code.');try{const r=await api('/api/test/fund',{method:'POST',body:JSON.stringify({amount,code})});toast(r.message);await refresh()}catch(e){toast(e.message)}}

function withdraw(){
 const d=S.data||{}; const eligible=Number(d.mainBalance||0)+Number(d.taskBalance||0)+Number(d.investmentProfit||0);
 const banks=['Barclays','HSBC UK','Lloyds Bank','NatWest','Santander UK','Halifax','Nationwide Building Society','Monzo','Revolut','JPMorgan Chase','Bank of America','Citibank','Wells Fargo','U.S. Bank','Capital One','Royal Bank of Canada (RBC)','TD Canada Trust','Scotiabank','Deutsche Bank','BNP Paribas','Société Générale','ING Bank','UniCredit','Banco Santander','BBVA','DBS Bank','OCBC Bank','United Overseas Bank (UOB)','Mizuho Bank','MUFG Bank','Bank of China','Industrial and Commercial Bank of China (ICBC)','Shinhan Bank','KB Kookmin Bank','Commonwealth Bank','ANZ','Westpac','National Australia Bank (NAB)'];
 return appShell(`<style>
 .withdraw-flow{max-width:820px;margin:auto}.withdraw-summary{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:20px}.withdraw-flow .form-card{padding:24px}.withdraw-flow .field{margin:14px 0}.withdraw-flow input{width:100%}.processing-page,.withdraw-status-page{max-width:720px;margin:10px auto;text-align:center}.processing-ring{width:145px;height:145px;border:10px solid #e5e8ee;border-top-color:var(--gold);border-radius:50%;margin:30px auto;display:grid;place-items:center;animation:spin 1.15s linear infinite}.processing-ring span{width:90px;height:90px;border-radius:50%;background:#fff;display:grid;place-items:center;font-size:25px;font-weight:800;color:var(--navy);animation:counterspin 1.15s linear infinite}.withdraw-notice{background:var(--gold);color:var(--navy);padding:22px;border-radius:18px;margin:28px 0;line-height:1.6}.progress-track2{height:11px;background:#e3e7ed;border-radius:20px;overflow:hidden}.progress-fill2{height:100%;background:var(--navy);width:0%;transition:width .5s}.status-card{text-align:left;padding:24px}.detail-row2{display:flex;justify-content:space-between;gap:18px;padding:13px 0;border-bottom:1px solid #edf0f4}.timeline2{margin:28px 0;text-align:left}.timeline-item2{display:flex;gap:14px;margin:18px 0}.marker2{width:28px;height:28px;border-radius:50%;background:var(--gold);color:var(--navy);display:grid;place-items:center;font-weight:800;flex:0 0 28px}.bottom-processing2{display:flex;gap:14px;align-items:center;background:#f7f2e8;border:1px solid #eadfc9;padding:18px;border-radius:14px;text-align:left}@keyframes spin{to{transform:rotate(360deg)}}@keyframes counterspin{to{transform:rotate(-360deg)}}@media(max-width:650px){.withdraw-summary{grid-template-columns:1fr}.detail-row2{flex-direction:column;gap:4px}}
 </style><div class="withdraw-flow"><div class="dash-title"><div><div class="kicker">withdrawal interface</div><h1>Withdraw</h1><p>Submit a withdrawal request using the full processing flow.</p></div></div><div class="withdraw-summary"><div class="card"><h3>Available to Withdraw</h3><div class="big-number">${fmt(eligible)}</div><p>Main wallet, task rewards and settled investment profit are included.</p></div><div class="card"><h3>Processing Status</h3><p>Requests move through a visual processing sequence for interface testing.</p></div></div><div class="card form-card"><form id="withdrawForm" onsubmit="event.preventDefault();submitWithdraw()"><div class="field"><label>Withdrawal Amount (£)</label><input id="withdrawAmount" type="number" min="1" step="0.01" max="${eligible}" placeholder="Enter amount" required></div><div class="field"><label>Bank</label><input id="withdrawBank" list="withdrawBankList" placeholder="Search or select a bank" required><datalist id="withdrawBankList">${banks.map(b=>`<option value="${b}"></option>`).join('')}</datalist></div><div class="field"><label>Recipient Name</label><input id="withdrawRecipient" type="text" placeholder="Enter recipient name" required></div><div class="field"><label>Account Number / IBAN</label><input id="withdrawIban" type="text" placeholder="Enter account number or IBAN" required></div><div class="field"><label>Mobile Number</label><input id="withdrawMobile" type="tel" placeholder="Enter mobile number" required></div><div class="field"><label>Email Address</label><input id="withdrawEmail" type="email" placeholder="Enter email address" required></div><button class="btn primary full-btn" type="submit">Continue to Processing</button></form></div></div>`)}

function submitWithdraw(){
 const form=document.getElementById('withdrawForm'); if(!form) return; const data={amount:Number(document.getElementById('withdrawAmount').value),bank:document.getElementById('withdrawBank').value.trim(),recipientName:document.getElementById('withdrawRecipient').value.trim(),iban:document.getElementById('withdrawIban').value.trim(),mobile -:document.getElementById('withdrawMobile').value.trim(),email:document.getElementById('withdrawEmail').value.trim()};
 if(!data.amount||data.amount<=0||!data.bank||!data.recipientName||!data.iban||!data.mobile||!data.email) return toast('Please complete all withdrawal details.'); showWithdrawalProcessing(data);
}

function showWithdrawalProcessing(data){
 const values=[0,10,20,30,40,50,65]; root.innerHTML=appShell(`<div class="processing-page"><div class="processing-ring"><span id="wpct">0%</span></div><h1>Processing your transaction</h1><p class="muted">Almost ready, please wait while your request is being prepared.</p><div class="withdraw-notice" id="wnotice">Your withdrawal request is being securely prepared for processing.</div><div class="card" style="padding:22px;text-align:left;margin-top:25px"><div style="display:flex;justify-content:space-between;margin-bottom:10px"><strong>Processing</strong><strong id="wprog">0%</strong></div><div class="progress-track2"><div class="progress-fill2" id="wfill"></div></div></div><div class="status" style="margin-top:25px">● <span id="wstatus">Processing your transaction...</span></div></div>`);
 let i=0; const timer=setInterval(()=>{const v=values[i++]; const p=document.getElementById('wpct'),pr=document.getElementById('wprog'),f=document.getElementById('wfill'); if(p)p.textContent=v+'%';if(pr)pr.textContent=v+'%';if(f)f.style.width=v+'%'; if(v===65){const n=document.getElementById('wnotice');if(n)n.textContent='Your withdrawal is still processing.';const st=document.getElementById('wstatus');if(st)st.textContent='Your withdrawal is still processing.';clearInterval(timer);setTimeout(()=>finalizeWithdrawal(data),900)}},500);
}

async function finalizeWithdrawal(data){try{const r=await api('/api/test/withdraw',{method:'POST',body:JSON.stringify({amount:data.amount})}); showWithdrawalStatus(data,r.message||'Your withdrawal has been processed.')}catch(e){toast(e.message);S.page='withdraw';render()}}

function showWithdrawalStatus(data,message){root.innerHTML=appShell(`<div class="withdraw-status-page"><div class="dash-title"><div><div class="kicker">Withdrawal request</div><h1>Withdrawal Status</h1><p>${esc(message)}</p></div></div><div class="card status-card"><div class="detail-row2"><span>Amount</span><strong>${fmt(data.amount)}</strong></div><div class="detail-row2"><span>Bank</span><strong>${esc(data.bank)}</strong></div><div class="detail-row2"><span>Recipient Name</span><strong>${esc(data.recipientName)}</strong></div><div class="detail-row2"><span>Account Number / IBAN</span><strong>${esc(data.iban)}</strong></div><div class="detail-row2"><span>Mobile</span><strong>${esc(data.mobile)}</strong></div><div class="detail-row2"><span>Email</span><strong>${esc(data.email)}</strong></div></div><div class="timeline2"><div class="timeline-item2"><div class="marker2">✓</div><div><h3>Withdrawal Requested</h3><p>Your withdrawal request has been received.</p></div></div><div class="timeline-item2"><div class="marker2">✓</div><div><h3>Approved</h3><p>Your request has passed the processing stage.</p></div></div><div class="timeline-item2"><div class="marker2">●</div><div><h3>Processed</h3><p>Your withdrawal has been processed.</p></div></div></div><div class="bottom-processing2"><div class="marker2">✓</div><div><strong>Processed</strong><p>This is a demonstration status flow. Your bank transacions is initiated by this interface.</p></div></div><button class="btn primary full-btn" style="margin-top:24px" onclick="refresh()">Return to Dashboard</button></div>`)}

function tasks(){const done=S.data?.dailyTaskCompletions||{};return appShell(`<div class="dash-title"><div><div class="kicker">Participate to earn</div><h1>Tasks to Earn</h1><p>Every task now opens a real interactive activity. Rewards are added only after valid completion.</p></div><div class="task-progress"><strong>${Object.keys(done).length}/10</strong><span>Completed</span></div></div><div class="task-list">${TASKS.map(t=>`<div class="task-row ${done[t[0]]?'task-done':''}"><div class="task-icon">${t[4]}</div><div class="task-content"><h3>${t[1]}</h3><p>${t[2]}</p></div><div class="task-reward">${fmt(t[3])}</div><button class="btn secondary" ${done[t[0]]?'disabled':''} onclick="openTask('${t[0]}')">${done[t[0]]?'Completed':'Start Task'}</button></div>`).join('')}</div>`)}

function openTask(id){const task=TASKS.find(t=>t[0]===id);if(!task)return;const title=task[1];let body='';
if(id==='dailyCheckIn') body=`<div class="task-modal"><p>Confirm that you are checking in today to receive the daily reward.</p><label class="checkline"><input id="tConfirm" type="checkbox"> I confirm my daily check-in.</label><button class="btn primary full-btn" onclick="submitTask('dailyCheckIn',{confirm:document.getElementById('tConfirm').checked})">Complete Check-in</button></div>`;
if(id==='financialKnowledgeQuiz') body=`<div class="task-modal"><p>Answer all three questions correctly.</p><div class="field"><label>1. A plan for tracking income and expenses is a:</label><select id="q1"><option value="">Choose</option><option value="budget">Budget</option><option value="loan">Loan</option></select></div><div class="field"><label>2. Spreading investments can support:</label><select id="q2"><option value="">Choose</option><option value="diversification">Diversification</option><option value="inflation">Inflation</option></select></div><div class="field"><label>3. The possibility of losing value is called:</label><select id="q3"><option value="">Choose</option><option value="risk">Risk</option><option value="profit">Profit</option></select></div><button class="btn primary full-btn" onclick="submitTask('financialKnowledgeQuiz',{q1:document.getElementById('q1').value,q2:document.getElementById('q2').value,q3:document.getElementById('q3').value})">Submit Quiz</button></div>`;
if(id==='investmentArticle') body=`<div class="task-modal"><article class="lesson"><h4>Why diversification matters</h4><p>Diversification means spreading exposure instead of relying on a single asset or category. In this lesson, the goal is simply to understand that concentration can increase the impact of one outcome.</p></article><label class="checkline"><input id="readArticle" type="checkbox"> I have read the lesson.</label><div class="field"><label>Write one takeaway (10+ characters)</label><textarea id="takeaway" placeholder="What did you learn?"></textarea></div><button class="btn primary full-btn" onclick="submitTask('investmentArticle',{read:document.getElementById('readArticle').checked,takeaway:document.getElementById('takeaway').value})">Submit Takeaway</button></div>`;
if(id==='cryptoMemoryPuzzle') body=`<div class="task-modal"><p>Select all four matching concept cards to complete the memory activity.</p><div class="memory-grid">${['Wallet','Block','Ledger','Key'].map(x=>`<button class="memory-card" onclick="toggleMemory(this,'${x}')">${x}</button>`).join('')}</div><p id="memoryStatus" class="label">0/4 selected</p><button class="btn primary full-btn" onclick="submitMemory()">Submit Puzzle</button></div>`;
if(id==='bitcoinJigsawPuzzle') body=`<div class="task-modal"><p>Unscramble this word: <strong>KCLOHBCIAN</strong></p><div class="field"><label>Your answer</label><input id="jigsawAnswer" placeholder="Enter the word"></div><button class="btn primary full-btn" onclick="submitTask('bitcoinJigsawPuzzle',{answer:document.getElementById('jigsawAnswer').value})">Check Answer</button></div>`;
if(id==='investmentEducation') body=`<div class="task-modal"><h4>Mini lesson: compounding</h4><p>Compounding describes growth being calculated on an amount that may already include previous growth. This activity is educational and does not promise any real-world return.</p><div class="field"><label>Choose the lesson keyword</label><select id="lesson"><option value="">Choose</option><option value="compound">Compound</option><option value="withdraw">Withdraw</option></select></div><label class="checkline"><input id="lessonConfirm" type="checkbox"> I completed the lesson.</label><button class="btn primary full-btn" onclick="submitTask('investmentEducation',{lesson:document.getElementById('lesson').value,confirm:document.getElementById('lessonConfirm').checked})">Complete Lesson</button></div>`;
if(id==='completeSurvey') body=`<div class="task-modal"><p>Please complete this short ValerisBank survey.</p><div class="field"><label>How would you rate this?</label><select id="surveyRating"><option value="">Choose</option><option value="excellent">Excellent</option><option value="good">Good</option><option value="average">Average</option><option value="poor">Poor</option></select></div><div class="field"><label>What would you improve?</label><textarea id="surveyFeedback" placeholder="At least 8 characters"></textarea></div><button class="btn primary full-btn" onclick="submitTask('completeSurvey',{rating:document.getElementById('surveyRating').value,feedback:document.getElementById('surveyFeedback').value})">Submit Survey</button></div>`;
if(id==='marketWatch') body=`<div class="task-modal"><p>market scenario: a chart moves from 100 to 108. Which direction did it move?</p><div class="choice-row"><button class="choice" onclick="pickChoice('up',this)">Up</button><button class="choice" onclick="pickChoice('down',this)">Down</button><button class="choice" onclick="pickChoice('flat',this)">Flat</button></div><button class="btn primary full-btn" onclick="submitTask('marketWatch',{direction:window.marketChoice||''})">Submit Observation</button></div>`;
if(id==='budgetPlanner') body=`<div class="task-modal"><p>Create a simple budget where planned needs and savings do not exceed income.</p><div class="field"><label>Monthly income</label><input id="budgetIncome" type="number" min="1"></div><div class="field"><label>Planned needs</label><input id="budgetNeeds" type="number" min="0"></div><div class="field"><label>Planned savings</label><input id="budgetSavings" type="number" min="0"></div><button class="btn primary full-btn" onclick="submitTask('budgetPlanner',{income:document.getElementById('budgetIncome').value,needs:document.getElementById('budgetNeeds').value,savings:document.getElementById('budgetSavings').value})">Validate Budget</button></div>`;
if(id==='securityCheck') body=`<div class="task-modal"><p>Tick all three good security practices.</p><label class="checkline"><input id="sec1" type="checkbox"> Use a strong, unique password.</label><label class="checkline"><input id="sec2" type="checkbox"> Check unexpected links for phishing.</label><label class="checkline"><input id="sec3" type="checkbox"> Use two-factor authentication where available.</label><button class="btn primary full-btn" onclick="submitTask('securityCheck',{password:document.getElementById('sec1').checked,phishing:document.getElementById('sec2').checked,twoFactor:document.getElementById('sec3').checked})">Complete Security Check</button></div>`;
modal(title,body)}
async function submitTask(id,payload){try{const r=await api('/api/test/tasks/'+id+'/submit',{method:'POST',body:JSON.stringify(payload)});closeModal();toast(r.message);await refresh()}catch(e){toast(e.message)}}
window.memoryChoices=[];
function toggleMemory(el,value){const list=window.memoryChoices||[];const i=list.indexOf(value);if(i>=0){list.splice(i,1);el.classList.remove('selected')}else if(list.length<4){list.push(value);el.classList.add('selected')}window.memoryChoices=list;const s=document.getElementById('memoryStatus');if(s)s.textContent=`${list.length}/4 selected`}
function submitMemory(){submitTask('cryptoMemoryPuzzle',{pairs:window.memoryChoices||[]})}
function pickChoice(value,el){window.marketChoice=value;document.querySelectorAll('.choice').forEach(b=>b.classList.remove('selected'));el.classList.add('selected')}

function investment(){const d=S.data||{};const active=activeInvestments();const activeHtml=active.map(i=>{const remaining=Math.max(0,new Date(i.maturesAt).getTime()-Date.now());const hours=Math.floor(remaining/3600000);const mins=Math.floor((remaining%3600000)/60000);return `<div class="investment-active"><div><span class="pill pending">Processing</span><h3>${fmt(i.amount)} investment</h3><p>Expected profit: <strong>${fmt(i.profit)}</strong></p></div><div class="countdown">${hours}h ${mins}m<small>until maturity</small></div></div>`}).join('');return appShell(`<div class="dash-title"><div><div class="kicker">24-hour return</div><h1>Investment</h1><p>Your funds and investments are all secured by Valerisbank.</p></div></div><div class="investment-layout"><div class="card investment-single"><div class="investment-badge">plan</div><h2>Valeris Investment</h2><div class="investment-rate">30%</div><p class="muted">Illustrative profit after 24 hours. At maturity, it returns the original capital plus the calculated profit to the member’s wallet.</p><div class="investment-meta"><div><span>Duration</span><strong>24 Hours</strong></div><div><span>Return</span><strong>30%</strong></div><div><span>Source</span><strong>Main Wallet</strong></div></div><div class="field"><label>Amount (£)</label><input id="investmentAmount" type="number" min="1" placeholder="Enter amount"></div><button class="btn primary full-btn" onclick="startInvestment()">Invest</button></div><div class="investment-side"><div class="card"><h3>Active Plans</h3>${activeHtml||'<p class="muted">No active investment.</p>'}</div><div class="card"><h3>Portfolio Snapshot</h3><div class="summary-line"><span>Active capital</span><strong>${fmt(d.investmentBalance)}</strong></div><div class="summary-line"><span>Settled profit</span><strong>${fmt(d.investmentProfit)}</strong></div></div></div></div>`)}
async function startInvestment(){const amount=Number(document.getElementById('investmentAmount')?.value);if(!amount||amount<=0)return toast('Enter a valid amount.');try{const r=await api('/api/test/invest',{method:'POST',body:JSON.stringify({amount})});toast(r.message);await refresh()}catch(e){toast(e.message)}}

function profile(){return appShell(`<div class="dash-title"><div><h1>Profile</h1><p>Your saved member details.</p></div></div><div class="cards profile-grid"><div class="card"><h3>Personal Information</h3><p>Name<br><strong>${esc(S.user?.firstName)} ${esc(S.user?.lastName)}</strong></p><p>Email<br><strong>${esc(S.user?.email)}</strong></p><p>Phone<br><strong>${esc(S.user?.phone)}</strong></p></div><div class="card"><h3>Account</h3><p>Account Number<br><strong>${esc(S.user?.accountNumber)}</strong></p><p>Country<br><strong>${esc(S.user?.country)}</strong></p></div><div class="card"><h3>Support</h3><p>Contact ValerisBank support directly on Telegram.</p><button class="btn primary" onclick="window.open('https://t.me/ValerisManagement','_blank')">Open Telegram Support</button></div></div>`)}
function infoPage(t,l){return shell(`<main class="section"><div class="container"><div class="kicker">ValerisBank</div><h1 style="font-size:44px">${esc(t)}</h1><p style="color:var(--muted);max-width:720px;line-height:1.7">${esc(l)}</p></div></main>`)}
function render(){let r;if(S.page==='home')r=home();else if(S.page==='login'||S.page==='signup')r=auth(S.page);else if(!S.user){S.page='login';r=auth('login')}else if(S.page==='dashboard')r=dashboard();else if(S.page==='transactions')r=transactions();else if(S.page==='fund')r=fund();else if(S.page==='withdraw')r=withdraw();else if(S.page==='tasks')r=tasks();else if(S.page==='investment')r=investment();else if(S.page==='profile')r=profile();else r=infoPage(S.page,'ValerisBank information page.');root.innerHTML=r}
(async()=>{await session();if(S.user)S.page='dashboard';render()})();
