const S={page:'home',token:localStorage.getItem('valeris_token')||'',user:null,data:null,balanceVisible:true};
const TASKS=[['dailyCheckIn','Daily Check-in','Complete today’s check-in.',50],['financialKnowledgeQuiz','Financial Knowledge Quiz','Complete the knowledge quiz.',100],['investmentArticle','Read an Investment Article','Review the learning article.',75],['cryptoMemoryPuzzle','Crypto Memory Puzzle','Complete the educational puzzle.',80],['bitcoinJigsawPuzzle','Bitcoin Jigsaw Puzzle','Complete the learning puzzle.',90],['investmentEducation','Investment Education','Complete the education activity.',120],['completeSurvey','Complete Survey','Submit feedback.',60],['marketWatch','Market Watch','Review the market summary.',70],['budgetPlanner','Budget Planner','Complete the budgeting exercise.',85],['securityCheck','Security Check','Complete the security awareness task.',65]];
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>'£'+Number(n||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
async function api(path,opt={}){let h={'Content-Type':'application/json',...(opt.headers||{})};if(S.token)h.Authorization='Bearer '+S.token;let r=await fetch(path,{...opt,headers:h});let d=await r.json().catch(()=>({message:'Server error'}));if(!r.ok)throw Error(d.message||'Request failed');return d}
function go(p){S.page=p;render();scrollTo(0,0)} function modal(t,b){mtitle.textContent=t;mbody.innerHTML=b;document.getElementById('modal').classList.remove('hidden')} function closeModal(){document.getElementById('modal').classList.add('hidden')} function toast(m){let e=document.getElementById('toast');if(!e){e=document.createElement('div');e.id='toast';e.className='toast';document.body.append(e)}e.textContent=m;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),3500)}
async function session(){if(!S.token)return;try{S.user=(await api('/api/me')).user;S.data=(await api('/api/me/data')).data}catch(e){S.token='';localStorage.removeItem('valeris_token')}} async function refresh(){S.data=(await api('/api/me/data')).data;render()}
function publicHeader(){return `<header class="header"><div class="container"><div class="logo" onclick="go('home')">VALERISBANK<small>EARN AND GROW</small></div><nav class="nav"><a onclick="go('personal')">Personal</a><a onclick="go('business')">Business</a><a onclick="go('products')">Products</a><a onclick="go('about')">About Us</a><a onclick="window.open('https://t.me/ValerisManagement','_blank')">Support</a></nav><div class="actions"><button class="btn outline" onclick="go('login')">Login</button><button class="btn primary" onclick="go('signup')">Open an Account</button></div></div></header>`}
function footer(){return `<footer class="footer"><div class="container"><div class="footgrid"><div><div class="logo">VALERISBANK<small>EARN AND GROW</small></div><p style="color:var(--muted);font-size:13px">Individual dashboards with saved demo data.</p></div><div><h4>Banking</h4><a>Personal Banking</a><a>Business Banking</a></div><div><h4>Company</h4><a onclick="go('about')">About Us</a></div><div><h4>Support</h4><a onclick="window.open('https://t.me/ValerisManagement','_blank')">Telegram Support</a></div></div><div class="copyright">© 2026 ValerisBank demo. No real money is processed.</div></div></footer>`} function shell(x){return publicHeader()+x+footer()}
function home(){return shell(`<main><section class="hero"><div class="container hero-grid"><div><div class="kicker">Digital account demo</div><h1>Banking Built Around Your Future.</h1><p>Each registered member has a separate saved dashboard, wallet, task rewards and activity.</p><div class="hero-buttons"><button class="btn primary" onclick="go('signup')">Open an Account</button><button class="btn outline" onclick="go('login')">Login</button></div><div class="hero-note">Demo environment • Server-side saved accounts • No real money</div></div><div class="mock"><div class="mock-top"><div><div class="balance-label">Available Balance</div><div class="balance">£24,580.00</div><div class="label">Valeris Account</div></div><span class="status">Demo active</span></div><div class="mock-grid"><div class="metric"><div class="label">Tasks</div><strong>Earn rewards</strong></div><div class="metric"><div class="label">Wallet</div><strong>Test funding</strong></div></div></div></div></section></main>`)}
function auth(type){return `<main class="auth"><div class="auth-card"><div class="logo">VALERISBANK<small>EARN AND GROW</small></div><h1>${type==='login'?'Welcome back':'Open your account'}</h1><div class="notice">Demo only. No real money, banking or investment transactions are processed.</div><div id="authMsg"></div>${type==='signup'?`<div class="field"><label>First name</label><input id="firstName"></div><div class="field"><label>Last name</label><input id="lastName"></div><div class="field"><label>Country</label><input id="country"></div><div class="field"><label>Phone</label><input id="phone"></div>`:''}<div class="field"><label>${type==='login'?'Email or phone':'Email'}</label><input id="email"></div><div class="field"><label>Password</label><input id="pass" type="password"></div><button class="btn primary" onclick="${type==='login'?'login()':'signup()'}">${type==='login'?'Login':'Create Account'}</button><button class="btn outline back" onclick="go('home')">Back</button></div></main>`}
function msg(m){let e=document.getElementById('authMsg');if(e)e.innerHTML=`<div class="notice">${esc(m)}</div>`}
async function signup(){try{let r=await api('/api/signup',{method:'POST',body:JSON.stringify({firstName:firstName.value,lastName:lastName.value,country:country.value,phone:phone.value,email:email.value,password:pass.value})});S.token=r.token;localStorage.setItem('valeris_token',S.token);S.user=r.user;await refresh();S.page='dashboard';render()}catch(e){msg(e.message)}}
async function login(){try{let r=await api('/api/login',{method:'POST',body:JSON.stringify({identity:email.value,password:pass.value})});S.token=r.token;localStorage.setItem('valeris_token',S.token);S.user=r.user;await refresh();S.page='dashboard';render()}catch(e){msg(e.message)}}
async function logout(){try{await api('/api/logout',{method:'POST'})}catch{}S.token='';S.user=null;S.data=null;localStorage.removeItem('valeris_token');go('home')}
function appbar(){return `<div class="appbar"><div class="container"><div class="logo" onclick="go('dashboard')">VALERISBANK<small>EARN AND GROW</small></div><div class="spacer"></div><div class="app-user"><span>${esc(S.user?.firstName||'Member')}</span><button class="btn" style="background:rgba(255,255,255,.1);color:#fff" onclick="go('profile')">Profile</button><button class="btn" style="background:transparent;color:#fff" onclick="logout()">Logout</button></div></div></div>`}
function side(){return `<aside class="sidebar"><h5>Banking</h5><button class="sidebtn" onclick="go('dashboard')">Overview</button><button class="sidebtn" onclick="go('fund')">Fund Wallet</button><button class="sidebtn" onclick="go('withdraw')">Withdraw</button><button class="sidebtn" onclick="go('tasks')">Tasks</button><button class="sidebtn" onclick="go('investment')">Investment</button><button class="sidebtn" onclick="go('transactions')">Transactions</button><h5>Account</h5><button class="sidebtn" onclick="go('profile')">Profile</button><button class="sidebtn" onclick="window.open('https://t.me/ValerisManagement','_blank')">Support</button><button class="sidebtn" onclick="logout()">Logout</button></aside>`}
function appShell(x){return appbar()+`<div class="dashboard">${side()}<main class="dashmain"><div class="notice" style="margin-bottom:16px">Simulation only: balances, funding, withdrawals, tasks and investments are test data.</div>${x}</main></div><nav class="mobile-nav"><button onclick="go('dashboard')">Home</button><button onclick="go('fund')">Fund</button><button onclick="go('withdraw')">Withdraw</button><button onclick="go('tasks')">Tasks</button><button onclick="logout()">Logout</button></nav>`}
function acts(){return (S.data?.activity||[]).slice().reverse()}
function dashboard(){let d=S.data||{},total=(+d.mainBalance||0)+(+d.taskBalance||0)+(+d.investmentProfit||0);return appShell(`<div class="dash-title"><div><h1>Welcome, ${esc(S.user?.firstName||'Member')}</h1><p>Your individual ValerisBank demo dashboard.</p></div></div><div class="stats"><div class="stat"><div class="label">Total Balance</div><div class="balance-row"><strong>${S.balanceVisible?fmt(total):'••••••••'}</strong><button class="balance-toggle" onclick="S.balanceVisible=!S.balanceVisible;render()">◉</button></div></div><div class="stat"><div class="label">Task Earnings</div><strong>${fmt(d.taskBalance)}</strong><div class="label">Withdrawable in demo</div></div><div class="stat"><div class="label">Investment Earnings</div><strong>${fmt(d.investmentProfit)}</strong></div></div><div class="quick"><button class="btn secondary" onclick="go('fund')">＋ Fund Wallet</button><button class="btn secondary" onclick="go('withdraw')">↗ Withdraw</button><button class="btn secondary" onclick="go('tasks')">☑ Tasks</button><button class="btn primary" onclick="go('investment')">▣ Investment</button></div><div class="panel-grid"><div class="panel"><h3>Recent Activity</h3><div class="tablewrap"><table class="table"><thead><tr><th>Description</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>${acts().slice(0,8).map(a=>`<tr><td>${esc(a.title)}</td><td>${esc(a.date)}</td><td>${fmt(a.amount)}</td><td><span class="pill ${a.status==='Pending'?'pending':'ok'}">${esc(a.status)}</span></td></tr>`).join('')||'<tr><td colspan="4">No activity yet.</td></tr>'}</tbody></table></div></div><div class="panel"><h3>Account Summary</h3><p class="label">Main wallet</p><strong>${fmt(d.mainBalance)}</strong><p class="label">Completed tasks: ${d.completedTasks||0}</p><p class="label">Account: ${esc(S.user?.accountNumber||'')}</p></div></div>`)}
function transactions(){return appShell(`<div class="dash-title"><div><h1>Transactions</h1><p>Saved demo account activity.</p></div></div><div class="panel"><div class="tablewrap"><table class="table"><thead><tr><th>Description</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>${acts().map(a=>`<tr><td>${esc(a.title)}</td><td>${esc(a.date)}</td><td>${fmt(a.amount)}</td><td>${esc(a.status)}</td></tr>`).join('')}</tbody></table></div></div>`)}
function fund(){return appShell(`<div class="dash-title"><div><h1>Fund Wallet</h1><p>Test funding with a one-time demo verification code.</p></div></div><div class="card" style="max-width:620px"><div class="field"><label>Funding Amount (£)</label><input id="fundAmount" type="number" min="1"></div><div class="field"><label>Method</label><select id="fundMethod"><option>Demo Bank Transfer</option><option>Demo Payment Method</option></select></div><button class="btn secondary" onclick="generateCode()">Generate Demo Code</button><div class="field" style="margin-top:15px"><label>Verification Code</label><input id="fundCode" maxlength="6" placeholder="Enter 6-digit code"></div><div class="notice">Code appears only in server/Render logs, expires after 5 minutes and is single-use.</div><button class="btn primary" style="margin-top:15px" onclick="verifyFunding()">Verify Funding</button></div>`)}
async function generateCode(){try{await api('/api/test/verification-code',{method:'POST'});toast('Code generated. Check server logs.')}catch(e){toast(e.message)}}
async function verifyFunding(){let amount=+fundAmount.value,code=fundCode.value.trim();if(!amount||amount<=0)return toast('Enter a valid amount.');try{let r=await api('/api/test/fund',{method:'POST',body:JSON.stringify({amount,code,method:fundMethod.value})});toast(r.message);await refresh();go('dashboard')}catch(e){toast(e.message)}}
function withdraw(){let d=S.data||{},eligible=(+d.mainBalance||0)+(+d.taskBalance||0)+(+d.investmentProfit||0);return appShell(`<div class="dash-title"><div><h1>Withdraw</h1><p>Request a simulated withdrawal from your eligible balance.</p></div></div><div class="card" style="max-width:620px"><div class="field"><label>Eligible Balance</label><input value="${fmt(eligible)}" readonly></div><div class="field"><label>Amount (£)</label><input id="withdrawAmount" type="number" min="1"></div><div class="field"><label>Destination Region</label><select id="withdrawRegion"><option>United Kingdom</option><option>United States</option><option>European Union</option><option>Asia Pacific</option><option>Other International</option></select></div><div class="field"><label>Destination Details</label><input id="withdrawDestination" placeholder="Demo destination"></div><button class="btn primary" onclick="submitWithdraw()">Submit Demo Withdrawal</button></div>`)}
async function submitWithdraw(){let amount=+withdrawAmount.value;if(!amount||amount<=0)return toast('Enter a valid amount.');try{let r=await api('/api/test/withdraw',{method:'POST',body:JSON.stringify({amount,region:withdrawRegion.value,destination:withdrawDestination.value})});modal('Withdrawal Status',`<div class="notice">${esc(r.message)}</div><div style="margin-top:18px;background:#f7e1a3;border-radius:99px;overflow:hidden"><div style="width:65%;background:#A66A00;color:#fff;padding:10px;text-align:center;font-size:12px;font-weight:800">Your withdrawal has been processed.</div></div>`);await refresh()}catch(e){toast(e.message)}}
function tasks(){let done=S.data?.dailyTaskCompletions||{};return appShell(`<div class="dash-title"><div><h1>Tasks</h1><p>10 demo tasks available.</p></div></div><div class="task-list">${TASKS.map(t=>`<div class="task-row"><div class="icon">✓</div><div class="task-content"><h3>${t[1]}</h3><p>${t[2]}</p></div><div class="task-reward">${fmt(t[3])}</div><button class="btn secondary" ${done[t[0]]?'disabled':''} onclick="completeTask('${t[0]}')">${done[t[0]]?'Completed':'Complete Task'}</button></div>`).join('')}</div>`)}
async function completeTask(id){try{let r=await api('/api/test/tasks/'+id+'/complete',{method:'POST'});toast(r.message);await refresh()}catch(e){toast(e.message)}}
function investment(){let d=S.data||{};return appShell(`<div class="dash-title"><div><h1>Investment</h1><p>Illustrative simulation only.</p></div></div><div class="card" style="max-width:700px"><h2>Valeris Growth Simulation</h2><p style="color:var(--muted)">This is not a real investment product and does not process real money.</p><div class="field"><label>Simulation Amount (£)</label><input id="investmentAmount" type="number" min="1"></div><button class="btn primary" onclick="startInvestment()">Start Simulation</button><p class="label" style="margin-top:14px">Simulated investment balance: ${fmt(d.investmentBalance)}</p></div>`)}
async function startInvestment(){let amount=+investmentAmount.value;if(!amount||amount<=0)return toast('Enter a valid amount.');try{let r=await api('/api/test/invest',{method:'POST',body:JSON.stringify({amount})});toast(r.message);await refresh()}catch(e){toast(e.message)}}
function profile(){return appShell(`<div class="dash-title"><div><h1>Profile</h1><p>Your saved member details.</p></div></div><div class="cards"><div class="card"><h3>Personal Information</h3><p>Name<br><strong>${esc(S.user?.firstName)} ${esc(S.user?.lastName)}</strong></p><p>Email<br><strong>${esc(S.user?.email)}</strong></p><p>Phone<br><strong>${esc(S.user?.phone)}</strong></p></div><div class="card"><h3>Account</h3><p>Account Number<br><strong>${esc(S.user?.accountNumber)}</strong></p><p>Country<br><strong>${esc(S.user?.country)}</strong></p></div><div class="card"><h3>Support</h3><p>Contact ValerisBank support directly on Telegram.</p><button class="btn primary" onclick="window.open('https://t.me/ValerisManagement','_blank')">Open Telegram Support</button></div></div>`)}
function infoPage(t,l){return shell(`<main class="section"><div class="container"><div class="kicker">ValerisBank</div><h1 style="font-size:44px">${esc(t)}</h1><p style="color:var(--muted);max-width:720px;line-height:1.7">${esc(l)}</p></div></main>`)}
function render(){let r;if(S.page==='home')r=home();else if(S.page==='login'||S.page==='signup')r=auth(S.page);else if(!S.user){S.page='login';r=auth('login')}else if(S.page==='dashboard')r=dashboard();else if(S.page==='transactions')r=transactions();else if(S.page==='fund')r=fund();else if(S.page==='withdraw')r=withdraw();else if(S.page==='tasks')r=tasks();else if(S.page==='investment')r=investment();else if(S.page==='profile')r=profile();else r=infoPage(S.page,'ValerisBank information page.');root.innerHTML=r}
(async()=>{await session();if(S.user)S.page='dashboard';render()})();
