const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const app=express(),PORT=process.env.PORT||3000,DB=path.join(__dirname,'db.json'),sessions=new Map(),codes=new Map();
app.use(express.json({limit:'1mb'}));
const read=()=>{try{if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify({users:{}},null,2));let d=JSON.parse(fs.readFileSync(DB,'utf8'));d.users??={};return d}catch(e){console.error(e);return {users:{}}}};
const write=d=>{let t=DB+'.tmp';fs.writeFileSync(t,JSON.stringify(d,null,2));fs.renameSync(t,DB)};
const norm=v=>String(v||'').trim().toLowerCase();
function hp(p,s=crypto.randomBytes(16).toString('hex')){return {s,h:crypto.scryptSync(p,s,64).toString('hex')}} function vp(p,h,s){try{let a=Buffer.from(crypto.scryptSync(p,s,64).toString('hex'),'hex'),b=Buffer.from(h,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
const pub=u=>({id:u.id,accountNumber:u.accountNumber,firstName:u.firstName,lastName:u.lastName,email:u.email,country:u.country,phone:u.phone,createdAt:u.createdAt});
const def=()=>({mainBalance:0,taskBalance:0,investmentBalance:0,taskEarnings:0,investmentProfit:0,completedTasks:0,dailyTaskCompletions:{},investments:[],activity:[]});
const stamp=()=>new Date().toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}); const act=(title,amount,status='Completed',description='')=>({id:crypto.randomUUID(),title,amount:Number(amount)||0,status,description,date:stamp()});
function auth(req,res,next){let h=req.headers.authorization||'',t=h.startsWith('Bearer ')?h.slice(7):'',id=sessions.get(t);if(!id)return res.status(401).json({message:'Your session has expired. Please log in again.'});let db=read(),u=db.users[id];if(!u)return res.status(401).json({message:'Account not found.'});Object.assign(req,{token:t,userId:id,user:u,db});next()} function save(req){req.db.users[req.userId]=req.user;write(req.db)}
app.post('/api/signup',(req,res)=>{let {firstName,lastName,email,country,phone,password}=req.body||{};if(!firstName||!lastName||!email||!country||!phone||!password)return res.status(400).json({message:'Please complete all required fields.'});if(String(password).length<8)return res.status(400).json({message:'Password must be at least 8 characters.'});let db=read(),e=norm(email),p=norm(phone);if(Object.values(db.users).some(u=>norm(u.email)===e||norm(u.phone)===p))return res.status(409).json({message:'An account with that email or phone already exists.'});let id=crypto.randomUUID(),x=hp(password),u={id,accountNumber:'VL'+String(Date.now()).slice(-8)+crypto.randomInt(10,100),firstName:String(firstName).trim(),lastName:String(lastName).trim(),email:e,country:String(country).trim(),phone:String(phone).trim(),passwordHash:x.h,passwordSalt:x.s,createdAt:new Date().toISOString(),data:def()};u.data.activity.push(act('Account Created',0));db.users[id]=u;write(db);let t=crypto.randomBytes(32).toString('hex');sessions.set(t,id);res.status(201).json({token:t,user:pub(u)})});
app.post('/api/login',(req,res)=>{let {identity,password}=req.body||{},db=read(),v=norm(identity),u=Object.values(db.users).find(x=>norm(x.email)===v||norm(x.phone)===v);if(!u||!vp(password,u.passwordHash,u.passwordSalt))return res.status(401).json({message:'Incorrect email/phone or password.'});let t=crypto.randomBytes(32).toString('hex');sessions.set(t,u.id);res.json({token:t,user:pub(u)})});
app.get('/api/me',auth,(req,res)=>res.json({user:pub(req.user)}));app.get('/api/me/data',auth,(req,res)=>res.json({data:req.user.data||def()}));app.post('/api/logout',auth,(req,res)=>{sessions.delete(req.token);res.json({ok:true})});
app.post('/api/test/verification-code',auth,(req,res)=>{let c=crypto.randomInt(100000,1000000).toString();codes.set(req.userId,{c,expires:Date.now()+300000});console.log(`[VALERIS DEMO OTP] user=${req.userId} code=${c} expires=5m`);res.json({ok:true,message:'Demo code generated.'})});
function check(id,c){let r=codes.get(id);if(!r||Date.now()>r.expires||String(c)!==r.c){if(r&&Date.now()>r.expires)codes.delete(id);return false}codes.delete(id);return true}
app.post('/api/test/fund',auth,(req,res)=>{let a=Number(req.body?.amount);if(!Number.isFinite(a)||a<=0)return res.status(400).json({message:'Enter a valid funding amount.'});if(!check(req.userId,req.body?.code))return res.status(400).json({message:'Invalid or expired verification code.'});req.user.data??=def();req.user.data.mainBalance+=a;req.user.data.activity.push(act('Demo Wallet Funding',a));save(req);res.json({ok:true,message:`Demo funding verified. £${a.toFixed(2)} added.`})});
const tasks={dailyCheckIn:['Daily Check-in',50],financialKnowledgeQuiz:['Financial Knowledge Quiz',100],investmentArticle:['Read an Investment Article',75],cryptoMemoryPuzzle:['Crypto Memory Puzzle',80],bitcoinJigsawPuzzle:['Bitcoin Jigsaw Puzzle',90],investmentEducation:['Investment Education',120],completeSurvey:['Complete Survey',60],marketWatch:['Market Watch',70],budgetPlanner:['Budget Planner',85],securityCheck:['Security Check',65]};
app.post('/api/test/tasks/:id/complete',auth,(req,res)=>{let t=tasks[req.params.id];if(!t)return res.status(404).json({message:'Task not found.'});req.user.data??=def();let d=req.user.data;if(d.dailyTaskCompletions[req.params.id])return res.status(400).json({message:'This task has already been completed.'});d.dailyTaskCompletions[req.params.id]=new Date().toISOString();d.taskBalance+=t[1];d.taskEarnings+=t[1];d.completedTasks++;d.activity.push(act('Task Reward: '+t[0],t[1]));save(req);res.json({ok:true,message:`Task completed. £${t[1].toFixed(2)} demo reward added.`})});
app.post('/api/test/withdraw',auth,(req,res)=>{let a=Number(req.body?.amount);req.user.data??=def();let d=req.user.data,total=d.mainBalance+d.taskBalance+d.investmentProfit;if(!a||a<=0)return res.status(400).json({message:'Enter a valid withdrawal amount.'});if(a>total)return res.status(400).json({message:'Withdrawal amount exceeds eligible demo balance.'});let rem=a;for(let k of ['mainBalance','taskBalance','investmentProfit']){let take=Math.min(d[k],rem);d[k]-=take;rem-=take;if(rem<=0)break}d.activity.push(act('Demo Withdrawal',-a));save(req);res.json({ok:true,message:'Your withdrawal has been processed.'})});
app.post('/api/test/invest',auth,(req,res)=>{let a=Number(req.body?.amount);req.user.data??=def();let d=req.user.data;if(!a||a<=0)return res.status(400).json({message:'Enter a valid amount.'});if(a>d.mainBalance)return res.status(400).json({message:'Simulation amount exceeds demo wallet balance.'});d.mainBalance-=a;d.investmentBalance+=a;let profit=Math.round(a*.3*100)/100;d.investmentProfit+=profit;d.activity.push(act('Investment Simulation',profit));save(req);res.json({ok:true,message:'Investment simulation completed.'})});
app.use(express.static(__dirname));app.get(/.*/,(req,res)=>res.sendFile(path.join(__dirname,'index.html')));app.listen(PORT,()=>console.log('ValerisBank demo running on '+PORT));
